// <auto-generated />
namespace AnThanhLam.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeVisitoer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeVisitoer));
        
        string IMigrationMetadata.Id
        {
            get { return "202108220913049_changeVisitoer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
